### ISSUE TITLE
Cant get the example to run on BoUoW

### ISSUE THREAD

**Issue by sandeepzgk** [planetoftheweb/learnangular#4]
Hello Ray,

Big time fan. First time angular 2 user.

Since yesterday i have been trying to get the example running. I cloned the repo and got to the last chapter ending branch and thats where i am trying to run.

I've been getting the same error over and over again. I changed my versions of node using n. I also now have completely reinstalled my BoUoW and setup node 6.9.5 with the appropriate npm from scratch without any previous node instances. Still i am getting the same error.

`0 info it worked if it ends with ok`
`1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]`
`2 info using npm@3.10.10`
`3 info using node@v6.9.5`
`4 verbose run-script [ 'prestart', 'start', 'poststart' ]`
`5 info lifecycle learn-angular@1.0.0~prestart: learn-angular@1.0.0`
`6 silly lifecycle learn-angular@1.0.0~prestart: no script for prestart, continuing`
`7 info lifecycle learn-angular@1.0.0~start: learn-angular@1.0.0`
`8 verbose lifecycle learn-angular@1.0.0~start: unsafe-perm in lifecycle true`
`9 verbose lifecycle learn-angular@1.0.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/mnt/c/Users/sande/Desktop/learnangular/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games`
`10 verbose lifecycle learn-angular@1.0.0~start: CWD: /mnt/c/Users/sande/Desktop/learnangular`
`11 silly lifecycle learn-angular@1.0.0~start: Args: [ '-c', 'tsc && concurrently "tsc -w" "lite-server" ' ]`
`12 silly lifecycle learn-angular@1.0.0~start: Returned: code: 1  signal: null`
`13 info lifecycle learn-angular@1.0.0~start: Failed to exec start script`
`14 verbose stack Error: learn-angular@1.0.0 start: `tsc && concurrently "tsc -w" "lite-server" ``
`14 verbose stack Exit status 1`
`14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)`
`14 verbose stack     at emitTwo (events.js:106:13)`
`14 verbose stack     at EventEmitter.emit (events.js:191:7)`
`14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)`
`14 verbose stack     at emitTwo (events.js:106:13)`
`14 verbose stack     at ChildProcess.emit (events.js:191:7)`
`14 verbose stack     at maybeClose (internal/child_process.js:877:16)`
`14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)`
`15 verbose pkgid learn-angular@1.0.0`
`16 verbose cwd /mnt/c/Users/sande/Desktop/learnangular`
`17 error Linux 3.4.0+`
`18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"`
`19 error node v6.9.5`
`20 error npm  v3.10.10`
`21 error code ELIFECYCLE`
`22 error learn-angular@1.0.0 start: `tsc && concurrently "tsc -w" "lite-server" ``
`22 error Exit status 1`
`23 error Failed at the learn-angular@1.0.0 start script 'tsc && concurrently "tsc -w" "lite-server" '.`
`23 error Make sure you have the latest version of node.js and npm installed.`
`23 error If you do, this is most likely a problem with the learn-angular package,`
`23 error not with npm itself.`
`23 error Tell the author that this fails on your system:`
`23 error     tsc && concurrently "tsc -w" "lite-server"`
`23 error You can get information on how to open an issue for this project with:`
`23 error     npm bugs learn-angular`
`23 error Or if that isn't available, you can get their info via:`
`23 error     npm owner ls learn-angular`
`23 error There is likely additional logging output above.`
`24 verbose exit [ 1, true ]`

Not really sure what i am doing wrong. I do see that typescript dependencies are installed locally and not via -g. But I guess none of those issues are the core concern.

**Comment by kajuberdut** [comment]
Opening tsconfig.json and changing:
    "target": "es5"
to "target": "es6"
worked for me.

**Comment by planetoftheweb** [comment]
I've updated the target to es2015, which hopefully will resolve the issue and be a bit more backwards compatible. This course is due for an update soon.
