### ISSUE TITLE
npm doesn't start npm-debug issue

### ISSUE THREAD

**Issue by romi012** [planetoftheweb/learnangular#7]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle learn-angular@1.0.0~prestart: learn-angular@1.0.0
6 silly lifecycle learn-angular@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle learn-angular@1.0.0~start: learn-angular@1.0.0
8 verbose lifecycle learn-angular@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle learn-angular@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\ROMI\desktop\learnangular\node_modules\.bin;C:\Users\ROMI\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\ROMI\bin;C:\product\11.2.0\dbhome_1\bin;E:\app\ROMI\product\11.2.0\dbhome_1\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn;C:\Program Files\Microsoft SQL Server\100\Tools\Binn;C:\Program Files\Microsoft SQL Server\100\DTS\Binn;C:\Program Files\Java\jdk1.7.0_75\bin;C:\Program Files\Java\jre7\bin;%OPENCV_BUILD%x64\vc10\bin;C:\Users\ROMI\SDK\tools;C:\Program Files (x86)\Skype\Phone;C:\Program Files\nodejs;C:\Program Files\Git\cmd;C:\Program Files\Java\jdk1.7.0_75\bin;C:\Users\ROMI\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
10 verbose lifecycle learn-angular@1.0.0~start: CWD: C:\Users\ROMI\desktop\learnangular
11 silly lifecycle learn-angular@1.0.0~start: Args: [ '/d /s /c', 'tsc && concurrently "tsc -w" "lite-server" ' ]
12 silly lifecycle learn-angular@1.0.0~start: Returned: code: 2  signal: null
13 info lifecycle learn-angular@1.0.0~start: Failed to exec start script
14 verbose stack Error: learn-angular@1.0.0 start: `tsc && concurrently "tsc -w" "lite-server" `
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid learn-angular@1.0.0
16 verbose cwd C:\Users\ROMI\desktop\learnangular
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.10.0
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error learn-angular@1.0.0 start: `tsc && concurrently "tsc -w" "lite-server" `
22 error Exit status 2
23 error Failed at the learn-angular@1.0.0 start script 'tsc && concurrently "tsc -w" "lite-server" '.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the learn-angular package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     tsc && concurrently "tsc -w" "lite-server"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs learn-angular
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls learn-angular
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by kajuberdut** [comment]
Opening tsconfig.json and changing:
    "target": "es5"
to "target": "es6"
worked for me.

**Comment by planetoftheweb** [comment]
I've updated the target to ES2015 in all the branches. That should fix this issue.
