### ISSUE TITLE
npm start fails on macOS 10.12, node.js 7.7.3

### ISSUE THREAD

**Issue by HogansHeros** [planetoftheweb/learnangular#8]
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.7.3
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! learn-angular@1.0.0 start: `tsc && concurrently "tsc -w" "lite-server" `
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the learn-angular@1.0.0 start script 'tsc && concurrently "tsc -w" "lite-server" '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the learn-angular package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && concurrently "tsc -w" "lite-server" 
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs learn-angular
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls learn-angular
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/nhogan/Developer/Lynda/LearnAgular2/npm-debug.log
SCLMAC-1002305:LearnAgular2 nhogan$

**Comment by calluna** [comment]
I have the same problem...

**Comment by calluna** [comment]
ok, though the output error was different, I tried the solution from the a previous opened issue, and it worked for this one as well:

"edit the tsconfig.json file in the root directory and change the target value there from "es5" to "es6"."

**Comment by planetoftheweb** [comment]
Updated the tsconfig file and changed the target to es6

**Comment by zoltanjere** [comment]
You have updated it only under the master branch. Every other branches still have the issue. Thx for the solution @calluna
